### ISSUE TITLE
Does not work with fish shell

### ISSUE THREAD

**Issue by TheMBL09898** [Amarakon55/cfetch#1]
Crashes after printing Shell.

`fish: Job 1, 'cfetch' terminated by signal SIGSEGV (Address boundary error)`

If run with bash still prints fish as Shell and

`Segmentation fault`

Seems as it detects default shell instead of current shell

**Comment by Amarakon55** [comment]
It is intended to print the default shell instead of the current shell. I will attempt to add an option for the running shell. Could you please submit a screenshot of the error so that I can see what it looks like?

Finally, do you run Linux and Xorg? Cfetch currently only works on Linux and Xorg.

**Comment by Amarakon55** [comment]
Hmm that is strange. For the purpose of testing I installed fish, set it as my default shell, and then ran cfetch again. It worked. Here is a screenshot:
https://imgur.com/a/8HQAUSn

The issue is on your side. I think you can fix it my doing these two things:
1. Update cfetch with app-portage/smart-live-rebuild
2. Run the command `cfetch --recache`

**Comment by Amarakon55** [comment]
Closing since no response.
